apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyword-detector-deployment
  labels:
    app: keyword-detector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keyword-detector
  template:
    metadata:
      labels:
        app: keyword-detector
    spec:
      containers:
      - name: keyword-detector-container
        image: shashankdeep1998/aiapp:latest
        ports:
        - containerPort: 5000 
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"