apiVersion: v1
kind: Service
metadata:
  name: keyword-detector-service
spec:
  selector:
    app: keyword-detector
  ports:
    - protocol: TCP
      port: 8000 
      targetPort: 5000 
  type: LoadBalancer