apiVersion: v1
kind: Service
metadata:
  name: ai-sentiment-app-service
spec:
  selector:
    app: ai-sentiment-app
  ports:
    - protocol: TCP
      port: 80 # External port for the service
      targetPort: 5000 # Port the container is listening on
  type: LoadBalancer # Creates an AWS Classic Load Balancer (or Network Load Balancer with annotations)